
// Articles
export const SET_ARTICLES = 'SET_ARTICLES'
export const SET_EDIT_ARTICLE = 'SET_EDIT_ARTICLE'
export const CLEAR_EDIT_ARTICLE = 'CLEAR_EDIT_ARTICLE'
export const SHOW_EDIT_ARTICLE_FORM = 'SHOW_EDIT_ARTICLE_FORM'
export const SHOW_DELETE_ARTICLE_FORM = 'SHOW_DELETE_ARTICLE_FORM'
export const UPDATE_EDIT_ARTICLE_TITLE = 'UPDATE_EDIT_ARTICLE_TITLE'
export const UPDATE_EDIT_ARTICLE_BODY = 'UPDATE_EDIT_ARTICLE_BODY'
export const UPDATE_EDIT_ARTICLE_AUTHOR_ID = 'UPDATE_EDIT_ARTICLE_AUTHOR_ID'
export const START_EDIT_ARTICLE_LOADING = 'START_EDIT_ARTICLE_LOADING'
export const STOP_EDIT_ARTICLE_LOADING = 'STOP_EDIT_ARTICLE_LOADING'
export const SET_EDIT_ARTICLE_ERROR_TEXT = 'SET_EDIT_ARTICLE_ERROR_TEXT'


// Authors
export const SET_AUTHORS = 'SET_AUTHORS'
export const SET_EDIT_AUTHOR = 'SET_EDIT_AUTHOR'
export const CLEAR_EDIT_AUTHOR = 'CLEAR_EDIT_AUTHOR'
export const SHOW_EDIT_AUTHOR_FORM = 'SHOW_EDIT_AUTHOR_FORM'
export const SHOW_DELETE_AUTHOR_FORM = 'SHOW_DELETE_AUTHOR_FORM'
export const UPDATE_EDIT_AUTHOR_NAME = 'UPDATE_EDIT_AUTHOR_NAME'
export const UPDATE_EDIT_AUTHOR_AGE = 'UPDATE_EDIT_AUTHOR_AGE'
export const UPDATE_EDIT_AUTHOR_SEX = 'UPDATE_EDIT_AUTHOR_SEX'
export const UPDATE_EDIT_AUTHOR_INTERESTS = 'UPDATE_EDIT_AUTHOR_INTERESTS'
export const UPDATE_EDIT_AUTHOR_AVATAR_NAME = 'UPDATE_EDIT_AUTHOR_AVATAR_NAME'
export const UPDATE_EDIT_AUTHOR_AVATAR_URL = 'UPDATE_EDIT_AUTHOR_AVATAR_URL'
export const UPDATE_EDIT_AUTHOR_AVATAR_FILE = 'UPDATE_EDIT_AUTHOR_AVATAR_FILE'
export const SET_EDIT_AUTHOR_ERROR_TEXT = 'SET_EDIT_AUTHOR_ERROR_TEXT'


// Interests
export const SET_INTERESTS = 'SET_INTERESTS'
export const SET_EDIT_INTEREST = 'SET_EDIT_INTEREST'
export const CLEAR_EDIT_INTEREST = 'CLEAR_EDIT_INTEREST'
export const SHOW_EDIT_INTEREST_FORM = 'SHOW_EDIT_INTEREST_FORM'
export const SHOW_DELETE_INTEREST_FORM = 'SHOW_DELETE_INTEREST_FORM'
export const UPDATE_EDIT_INTEREST_NAME = 'UPDATE_EDIT_INTEREST_NAME'
export const SET_EDIT_INTEREST_ERROR_TEXT = 'SET_EDIT_INTEREST_ERROR_TEXT'
