
// Articles
export const SET_ARTICLES = 'SET_ARTICLES'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const SET_EDIT_ARTICLE = 'SET_EDIT_ARTICLE'
export const CLEAR_EDIT_ARTICLE = 'CLEAR_EDIT_ARTICLE'
export const SHOW_EDIT_ARTICLE_FORM = 'SHOW_EDIT_ARTICLE_FORM'
export const SHOW_DELETE_ARTICLE_FORM = 'SHOW_DELETE_ARTICLE_FORM'
export const UPDATE_EDIT_ARTICLE_TITLE = 'UPDATE_EDIT_ARTICLE_TITLE'
export const UPDATE_EDIT_ARTICLE_BODY = 'UPDATE_EDIT_ARTICLE_BODY'
export const UPDATE_EDIT_ARTICLE_AUTHOR_ID = 'UPDATE_EDIT_ARTICLE_AUTHOR_ID'
export const START_EDIT_ARTICLE_LOADING = 'START_EDIT_ARTICLE_LOADING'
export const STOP_EDIT_ARTICLE_LOADING = 'STOP_EDIT_ARTICLE_LOADING'
export const SET_EDIT_ARTICLE_ERROR_TEXT = 'SET_EDIT_ARTICLE_ERROR_TEXT'


// Authors
export const SET_AUTHORS = 'SET_AUTHORS'
export const SET_AUTHOR_INTEREST = 'SET_AUTHOR_INTEREST'


// Interests
export const SET_INTERESTS = 'SET_INTERESTS'

